### PR TITLE
feat: implement next theme

### PR DESCRIPTION
**Pull request by omarouhra**

### CODE REVIEW

**Comment by Nutlope** [comment]
Wow, thanks so much for this contribution @omarouhra! Would love to add light mode but I noticed your PR also overwrote a bunch of the font/text/spacing styles that I have. Look at this side by side of the original site to the right and your PR to the left.

As soon as we get that figured out, I'm good to move forward :)

CleanShot 2022-07-26 at 13 02 15@2x

**Comment by omarouhra** [comment]
Thank you @Nutlope  for the feedback I'll make sure to fix that Asap!

**Comment by Nutlope** [comment]
Hi @omarouhra! This looks really good. Two more quick things:
- Can we add some margin/padding to align the icon with the width of the page, and make sure there's padding so it doesn't stick right to the edge on mobile view? Take a look at the picture below to see what I mean
- Can you change all the classNames in the pages back to double quotes instead of single? This was probably a built in setting that you have on VSCode that switched everything and is making the PR a little hard to review

We should be good to merge after these two changes!
 
CleanShot 2022-07-28 at 21 09 27@2x

**Comment by Nutlope** [comment]
Thanks so much for the contribution! Feel free to submit another PR to add your name to the README :)

**Pull request merged**
