### PR TITLE
feat: add my article about DevRel

### PR DESCRIPTION
**Pull request by Baroshem**
Hey! 

Really great stuff that I have added to my bookmarks instantly. Keep doing the great work!

I recently wrote an article that could be useful for this website that covers the same topic and shares my take on DevRel (even with the fact that I am oficially working in another role ;)). This article was featured in Vue Dev.to and Global Dev.to Twitter and got many views and reactions.

In the upcoming days I will also add some other resources and maybe write something as well.

If you like, you can also put me in the contributors section, or I can add myself there if you agree :)

Let's share great knowledge about DevRel ❤️

### CODE REVIEW

**Comment by Nutlope** [comment]
Great article, I'm good with adding it to the list! One thing though, can you keep the title under 37 characters so it doesn't take up two lines? Maybe something like, "Doing DevRel Today"?

Once you make this change, I'm good to merge :) Also feel free to add yourself to the contributor list in the README.

**Comment by Baroshem** [comment]
@Nutlope 

Hey, thanks for the recommendation. I have updated the title and added contributor. 

If you like, you can merge it right now. I am planning to write a bit more for this website about DevRel so if you prefer we can keep it as a part of this PR or I can create a new one (will probably develop this in the upcoming days) :)

**Comment by Nutlope** [comment]
Hey @Baroshem! I'm not adding folks on the website as I'm only keeping the original authors there. I am adding contributors to the README though so please update your PR with that.

For contributing writing, please check with me on what you want to add so you don't put in a bunch of work that doesn't make it into the website.

**Comment by Baroshem** [comment]
Hey @Nutlope 

No worries. I have reverted the changes so there is only Contributor in package.json and my article. You can merge it now if you like :)

**Comment by Nutlope** [comment]
Merged. Thanks for the contribution!

**Pull request merged**
